(function(){
const DB='siteledger-offline-v1',STORE='drawing-pdfs',BUCKET='project-drawings';
let dbp=null;
function db(){if(dbp)return dbp;dbp=new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return dbp}
async function get(id){const d=await db();return new Promise((ok,no)=>{const q=d.transaction(STORE).objectStore(STORE).get(id);q.onsuccess=()=>ok(q.result||null);q.onerror=()=>no(q.error)})}
async function put(x){const d=await db();return new Promise((ok,no)=>{const q=d.transaction(STORE,'readwrite').objectStore(STORE).put(x);q.onsuccess=()=>ok(x);q.onerror=()=>no(q.error)})}
async function del(id){const d=await db();return new Promise((ok,no)=>{const q=d.transaction(STORE,'readwrite').objectStore(STORE).delete(id);q.onsuccess=()=>ok();q.onerror=()=>no(q.error)})}
async function signed(path){const enc=path.split('/').map(encodeURIComponent).join('/'),r=await fetch(`${SB}/storage/v1/object/sign/${BUCKET}/${enc}`,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:'{"expiresIn":600}'}),x=await r.json();if(!r.ok)throw new Error(x.message||'Could not download drawing');const u=x.signedURL||x.signedUrl;return /^https?:/.test(u)?u:`${SB}/storage/v1${u}`}
window.siteLedgerOfflineDrawing={
 async has(id){return !!(await get(id))},
 async bytes(id){const x=await get(id);return x?.blob?new Uint8Array(await x.blob.arrayBuffer()):null},
 async save(d){const u=await signed(d.storage_path),r=await fetch(u);if(!r.ok)throw new Error('Drawing download failed');const blob=await r.blob();await put({id:d.id,project_id:d.project_id,folder_id:d.folder_id||null,title:d.title||d.original_filename||'Drawing',storage_path:d.storage_path,blob,size:blob.size,saved_at:Date.now()});return blob.size},
 async remove(id){await del(id)}
};
window.downloadDrawingOffline=async function(id,btn){try{btn&&(btn.disabled=true,btn.textContent='Downloading…');const d=(await rest(`drawings?select=*&id=eq.${id}&limit=1`))[0];if(!d)throw new Error('Drawing not found');await siteLedgerOfflineDrawing.save(d);btn&&(btn.disabled=false,btn.textContent='✓ Offline');await decorate()}catch(e){btn&&(btn.disabled=false,btn.textContent='Offline');alert(e.message)}};
window.removeDrawingOffline=async function(id){if(!confirm('Remove the offline copy from this device? The drawing stays in SiteLedger.'))return;await siteLedgerOfflineDrawing.remove(id);await decorate()};
window.downloadFolderOffline=async function(folderId,btn){try{btn.disabled=true;const all=await rest(`drawings?select=*&project_id=eq.${route.projectId}&status=neq.archived`),fs=await rest(`drawing_folders?select=*&project_id=eq.${route.projectId}`),ids=new Set([folderId]);let changed=true;while(changed){changed=false;for(const f of fs)if(ids.has(f.parent_folder_id)&&!ids.has(f.id)){ids.add(f.id);changed=true}}const list=all.filter(d=>ids.has(d.folder_id));if(!list.length)throw new Error('No drawings in this folder.');let done=0;for(const d of list){btn.textContent=`Downloading ${++done}/${list.length}`;await siteLedgerOfflineDrawing.save(d)}btn.disabled=false;btn.textContent='✓ Folder Offline';await decorate()}catch(e){btn.disabled=false;btn.textContent='Download Offline';alert(e.message)}};
async function decorate(){if(route?.screen!=='drawings')return;const cards=[...document.querySelectorAll('.card.sl-file')];for(const c of cards){const main=c.querySelector('.sl-file-main'),m=(main?.getAttribute('onclick')||'').match(/drawing['"],['"]([^'"]+)/);if(!m||c.querySelector('.sl-offline-btn'))continue;const id=m[1],yes=await siteLedgerOfflineDrawing.has(id),b=document.createElement('button');b.className='btn secondary smallbtn sl-offline-btn';b.textContent=yes?'✓ Offline':'Offline';b.onclick=e=>{e.stopPropagation();yes?removeDrawingOffline(id):downloadDrawingOffline(id,b)};c.querySelector('.row')?.appendChild(b)}
 const actions=document.querySelector('.sl-draw-actions');if(actions&&ds?.folderId&&!document.getElementById('sl_folder_offline')){const b=document.createElement('button');b.id='sl_folder_offline';b.className='btn secondary';b.textContent='Download Folder Offline';b.onclick=()=>downloadFolderOffline(ds.folderId,b);actions.appendChild(b)}
}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>decorate().catch(()=>{}),80)}).observe(document.getElementById('app'),{childList:true,subtree:true});})();