(function(){
const q=id=>document.getElementById(id),oldOpenRFI=window.openRFI;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const label=r=>`RFI-${String(r.rfi_number).padStart(3,'0')}`,split=v=>String(v||'').split(/[;,\s]+/).map(x=>x.trim()).filter(Boolean),valid=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
async function ctx(id){const r=(await rest(`rfis?select=*&id=eq.${id}&limit=1`))[0],p=(await rest(`projects?select=*&id=eq.${r.project_id}&limit=1`))[0];const[a,b]=await Promise.all([rest(`rfi_attachments?select=id&rfi_id=eq.${id}&attachment_type=eq.drawing_snapshot`),rest(`rfi_photos?select=id&rfi_id=eq.${id}`)]);return{r,p,drawings:a.length,photos:b.length}}
function subject(c){return `${label(c.r)} – ${c.r.subject} – ${c.p?.name||'Project'}`}
function body(c){const due=c.r.due_date?`\nPlease provide direction by ${c.r.due_date} if possible.`:'',refs=[c.drawings&&`${c.drawings} marked-up drawing page${c.drawings===1?'':'s'}`,c.photos&&`${c.photos} photo${c.photos===1?'':'s'}`].filter(Boolean);return `Hi,\n\nPlease see attached ${label(c.r)} – ${c.r.subject} for ${c.p?.name||'the project'}.\n\nQuestion / Request:\n${c.r.question||'Please review the attached RFI and provide direction.'}${due}${refs.length?`\n\nThe attached RFI package includes ${refs.join(' and ')} for reference.`:''}\n\nThank you,\nRAF General Contracting Corp.`}
window.openRfiEmailComposer=async id=>{try{const c=await ctx(id),conn=(await rest('user_email_connections?select=id,provider,email_address&is_default=eq.true&limit=1'))[0],pre=valid(c.r.assigned_to||'')?c.r.assigned_to:'';modal(`<h2>Send ${label(c.r)}</h2><div class="small" style="margin-bottom:14px">${conn?`Sending from <b>${esc(conn.email_address)}</b>.`:'No sending mailbox connected.'} The generated RFI PDF will be attached to the email.</div><div class="field"><label>To</label><input id="rfi_mail_to" value="${esc(pre)}"></div><div class="field"><label>CC</label><input id="rfi_mail_cc"></div><div class="field"><label>Subject</label><input id="rfi_mail_subject" value="${esc(subject(c))}"></div><div class="field"><label>Message</label><textarea id="rfi_mail_body" rows="12">${esc(body(c))}</textarea></div><div id="rfi_mail_status"></div><div class="actions"><button class="btn secondary" onclick="openEmailSettings()">Email Settings</button><button class="btn secondary" onclick="closeModal()">Cancel</button><button id="rfi_mail_send" class="btn primary" onclick="sendRfiDirect('${id}')">Send RFI</button></div>`)}catch(e){alert(e.message||'Could not prepare RFI email.')}};
function b64(blob){return new Promise((res,rej)=>{const f=new FileReader();f.onload=()=>res(String(f.result).split(',')[1]);f.onerror=rej;f.readAsDataURL(blob)})}
window.sendRfiDirect=async id=>{const btn=q('rfi_mail_send'),stat=q('rfi_mail_status');try{const to=split(q('rfi_mail_to').value),cc=split(q('rfi_mail_cc').value),sub=q('rfi_mail_subject').value.trim(),msg=q('rfi_mail_body').value.trim();if(!to.length)return alert('Enter at least one recipient.');const bad=[...to,...cc].filter(x=>!valid(x));if(bad.length)return alert(`Check email address: ${bad[0]}`);btn.disabled=true;btn.textContent='Building PDF…';const out=await window.buildRfiPdfPackage(id),blob=out.doc.output('blob');btn.textContent='Sending…';const res=await fetch(`${SB}/functions/v1/send-rfi-email`,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({rfi_id:id,to,cc,subject:sub,message:msg,pdf_filename:out.filename,pdf_base64:await b64(blob)})}),d=await res.json();if(!res.ok){if(d.error==='NO_EMAIL_CONNECTION'){stat.innerHTML='<div class="notice">Connect an email account first.</div>';return}throw new Error(d.message||'Could not send RFI.')}closeModal();await rest('rfi_transmissions',{method:'POST',body:JSON.stringify({rfi_id:id,channel:'direct_email',to_emails:to,cc_emails:cc,subject:sub,body:msg,status:'sent',attachment_filename:out.filename,sent_at:new Date().toISOString(),created_by:me.id})});await rest(`rfis?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({status:'open',sent_at:new Date().toISOString(),updated_at:new Date().toISOString()})});openRFI(id)}catch(e){stat.innerHTML=`<div class="notice">${esc(e.message||'Could not send RFI.')}</div>`}finally{if(btn){btn.disabled=false;btn.textContent='Send RFI'}}};
async function install(id){const page=document.querySelector('.page');if(!page||q('sl_rfi_send_btn'))return;const hero=page.querySelector('.hero');if(!hero)return;let bar=hero.nextElementSibling;if(!bar||!bar.classList.contains('actions')){bar=document.createElement('div');bar.className='actions';bar.style.marginTop='12px';hero.insertAdjacentElement('afterend',bar)}const b=document.createElement('button');b.id='sl_rfi_send_btn';b.className='btn primary';b.textContent='✉ Send RFI';b.onclick=()=>openRfiEmailComposer(id);bar.insertBefore(b,bar.firstChild);const rows=await rest(`rfi_transmissions?select=*&rfi_id=eq.${id}&order=created_at.desc&limit=10`),sec=document.createElement('div');sec.innerHTML=`<div class="section">Email / Transmission History</div>${rows.map(t=>`<div class="card"><div class="title">${esc(t.subject)}</div><div class="small">${esc((t.to_emails||[]).join(', '))} · ${new Date(t.created_at).toLocaleString()} · ${esc(t.status.toUpperCase())}</div></div>`).join('')||'<div class="card empty">No RFI emails sent yet.</div>'}`;page.appendChild(sec)}
window.openRFI=async id=>{const x=await oldOpenRFI(id);requestAnimationFrame(()=>install(id));return x};
})();