(function(){
const q=id=>document.getElementById(id);
const oldOpenRFI=window.openRFI;
const escEmail=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const rfiLabel=r=>`RFI-${String(r.rfi_number).padStart(3,'0')}`;
const splitEmails=v=>String(v||'').split(/[;,\s]+/).map(x=>x.trim()).filter(Boolean);
const looksEmail=v=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v);
async function rfiContext(id){const r=(await rest(`rfis?select=*&id=eq.${id}&limit=1`))[0];if(!r)throw new Error('RFI not found.');const p=(await rest(`projects?select=*&id=eq.${r.project_id}&limit=1`))[0];const [atts,photos]=await Promise.all([rest(`rfi_attachments?select=id&rfi_id=eq.${id}&attachment_type=eq.drawing_snapshot`),rest(`rfi_photos?select=id&rfi_id=eq.${id}`)]);return{r,p,drawings:atts.length,photos:photos.length}}
function defaultSubject(c){return `${rfiLabel(c.r)} – ${c.r.subject} – ${c.p?.name||'Project'}`}
function defaultBody(c){const due=c.r.due_date?`\nPlease provide direction by ${c.r.due_date} if possible.`:'';const support=[];if(c.drawings)support.push(`${c.drawings} marked-up drawing page${c.drawings===1?'':'s'}`);if(c.photos)support.push(`${c.photos} photo${c.photos===1?'':'s'}`);const refs=support.length?`\n\nThe RFI package includes ${support.join(' and ')} for reference.`:'';return `Hi,\n\nPlease see ${rfiLabel(c.r)} – ${c.r.subject} for ${c.p?.name||'the project'}.\n\nQuestion / Request:\n${c.r.question||'Please review the attached RFI and provide direction.'}${due}${refs}\n\nThank you,\nRAF General Contracting Corp.`}
window.openRfiEmailComposer=async function(id){try{const c=await rfiContext(id),prefill=looksEmail(c.r.assigned_to||'')?c.r.assigned_to:'';modal(`<h2>Send ${rfiLabel(c.r)}</h2><div class="small" style="margin-bottom:14px">SiteLedger will generate the RFI PDF package and prepare the email. You can edit everything before sending.</div><div class="field"><label>To</label><input id="rfi_mail_to" type="email" multiple placeholder="architect@company.com" value="${escEmail(prefill)}"></div><div class="field"><label>CC</label><input id="rfi_mail_cc" placeholder="pm@company.com; owner@company.com"></div><div class="field"><label>Subject</label><input id="rfi_mail_subject" value="${escEmail(defaultSubject(c))}"></div><div class="field"><label>Message</label><textarea id="rfi_mail_body" rows="12">${escEmail(defaultBody(c))}</textarea></div><div class="small">Primary option opens your email app with recipients, subject, message and a secure PDF link. “Share PDF Attachment” uses the device share sheet and includes the actual PDF file.</div><div id="rfi_mail_status"></div><div class="actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn secondary" onclick="shareRfiEmailAttachment('${id}')">Share PDF Attachment</button><button id="rfi_mail_send" class="btn primary" onclick="prepareRfiEmail('${id}')">Open Email</button></div>`)}catch(e){alert(e.message||'Could not prepare RFI email.')}};
async function uploadPdf(c,blob,filename){const safe=filename.replace(/[^a-zA-Z0-9._-]+/g,'-'),path=`${c.r.project_id}/${c.r.id}/issued/${Date.now()}-${safe}`;const res=await fetch(`${SB}/storage/v1/object/rfi-files/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/pdf','x-upsert':'false'},body:blob});let d={};try{d=await res.json()}catch(_){}if(!res.ok)throw new Error(d.message||'Could not store RFI PDF.');return path}
async function signed(path){const res=await fetch(`${SB}/storage/v1/object/sign/rfi-files/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:604800})});const d=await res.json();if(!res.ok)throw new Error(d.message||'Could not create RFI PDF link.');const u=d.signedURL||d.signedUrl;return /^https?:/.test(u)?u:`${SB}/storage/v1${u}`}
async function logTransmission(id,data){const rows=await rest('rfi_transmissions',{method:'POST',body:JSON.stringify({rfi_id:id,channel:data.channel||'email_link',to_emails:data.to,cc_emails:data.cc,subject:data.subject,body:data.body,status:data.status||'prepared',attachment_filename:data.filename||null,attachment_storage_path:data.path||null,created_by:me.id})});return rows[0]}
window.prepareRfiEmail=async function(id){const btn=q('rfi_mail_send'),stat=q('rfi_mail_status');try{const to=splitEmails(q('rfi_mail_to').value),cc=splitEmails(q('rfi_mail_cc').value),subject=q('rfi_mail_subject').value.trim(),body=q('rfi_mail_body').value.trim();if(!to.length)return alert('Enter at least one recipient email.');const bad=[...to,...cc].filter(x=>!looksEmail(x));if(bad.length)return alert(`Check email address: ${bad[0]}`);if(!subject)return alert('Enter an email subject.');btn.disabled=true;btn.textContent='Building RFI…';if(stat)stat.innerHTML='<div class="small" style="margin-top:10px">Generating and storing the RFI PDF…</div>';const c=await rfiContext(id),out=await window.buildRfiPdfPackage(id),blob=out.doc.output('blob'),path=await uploadPdf(c,blob,out.filename),url=await signed(path),fullBody=`${body}\n\nRFI PDF (secure link valid for 7 days):\n${url}`;const tx=await logTransmission(id,{channel:'email_link',to,cc,subject,body,filename:out.filename,path,status:'shared'});await rest(`rfi_transmissions?id=eq.${tx.id}`,{method:'PATCH',body:JSON.stringify({shared_at:new Date().toISOString()})});const mailto=`mailto:${encodeURIComponent(to.join(','))}?${cc.length?`cc=${encodeURIComponent(cc.join(','))}&`:''}subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(fullBody)}`;closeModal();window.location.href=mailto;setTimeout(()=>openRFI(id),700)}catch(e){if(stat)stat.innerHTML=`<div class="notice">${escEmail(e.message||'Could not prepare email.')}</div>`;else alert(e.message||'Could not prepare email.')}finally{if(btn){btn.disabled=false;btn.textContent='Open Email'}}};
window.shareRfiEmailAttachment=async function(id){const stat=q('rfi_mail_status');try{const to=splitEmails(q('rfi_mail_to').value),cc=splitEmails(q('rfi_mail_cc').value),subject=q('rfi_mail_subject').value.trim(),body=q('rfi_mail_body').value.trim(),out=await window.buildRfiPdfPackage(id),blob=out.doc.output('blob'),file=new File([blob],out.filename,{type:'application/pdf'});if(!(navigator.share&&navigator.canShare?.({files:[file]})))return alert('This device cannot share a PDF attachment directly. Use Open Email instead.');const tx=await logTransmission(id,{channel:'email_share',to,cc,subject,body,filename:out.filename,status:'shared'});await navigator.share({title:subject,text:body,files:[file]});await rest(`rfi_transmissions?id=eq.${tx.id}`,{method:'PATCH',body:JSON.stringify({shared_at:new Date().toISOString()})});closeModal();setTimeout(()=>openRFI(id),250)}catch(e){if(e?.name!=='AbortError'){if(stat)stat.innerHTML=`<div class="notice">${escEmail(e.message||'Could not share RFI.')}</div>`;else alert(e.message||'Could not share RFI.')}}};
window.markRfiTransmissionSent=async function(txId,rfiId){await rest(`rfi_transmissions?id=eq.${txId}`,{method:'PATCH',body:JSON.stringify({status:'sent',sent_at:new Date().toISOString()})});await rest(`rfis?id=eq.${rfiId}`,{method:'PATCH',body:JSON.stringify({status:'open',sent_at:new Date().toISOString(),updated_at:new Date().toISOString()})});openRFI(rfiId)};
async function install(id){const page=document.querySelector('.page');if(!page||q('sl_rfi_send_btn'))return;const hero=page.querySelector('.hero');if(!hero)return;let actionBar=hero.nextElementSibling;if(!actionBar||!actionBar.classList.contains('actions')){actionBar=document.createElement('div');actionBar.className='actions';actionBar.style.marginTop='12px';hero.insertAdjacentElement('afterend',actionBar)}const send=document.createElement('button');send.id='sl_rfi_send_btn';send.className='btn primary';send.textContent='✉ Send RFI';send.onclick=()=>openRfiEmailComposer(id);actionBar.insertBefore(send,actionBar.firstChild);const rows=await rest(`rfi_transmissions?select=*&rfi_id=eq.${id}&order=created_at.desc&limit=10`);const sec=document.createElement('div');sec.id='sl_rfi_transmissions';sec.innerHTML=`<div class="section">Email / Transmission History</div>${rows.map(t=>`<div class="card"><div class="row"><div><div class="title">${escEmail(t.subject)}</div><div class="small">${escEmail((t.to_emails||[]).join(', ')||'No recipient')} · ${new Date(t.created_at).toLocaleString()} · ${escEmail(t.status.toUpperCase())}</div></div>${t.status!=='sent'?`<button class="btn secondary smallbtn" onclick="markRfiTransmissionSent('${t.id}','${id}')">Mark Sent</button>`:''}</div></div>`).join('')||'<div class="card empty">No RFI emails prepared yet.</div>'}`;const actions=[...page.querySelectorAll('.section')].find(x=>x.textContent.trim()==='RFI Actions');if(actions)actions.insertAdjacentElement('beforebegin',sec);else page.appendChild(sec)}
window.openRFI=async function(id){const out=await oldOpenRFI(id);requestAnimationFrame(()=>install(id));return out};
})();