(function(){
const q=id=>document.getElementById(id),enc=p=>p.split('/').map(encodeURIComponent).join('/'),safe=n=>String(n||'photo').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-');
const oldOpenRFI=window.openRFI;
async function sign(path){const res=await fetch(`${SB}/storage/v1/object/sign/rfi-files/${enc(path)}`,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});const d=await res.json();if(!res.ok)throw new Error(d.message||'Could not open photo');const u=d.signedURL||d.signedUrl;return /^https?:/.test(u)?u:`${SB}/storage/v1${u}`}
async function upload(path,file){const res=await fetch(`${SB}/storage/v1/object/rfi-files/${enc(path)}`,{method:'POST',headers:{apikey:KEY,Authorization:'Bearer '+token,'Content-Type':file.type||'image/jpeg','x-upsert':'false'},body:file});if(!res.ok){let d={};try{d=await res.json()}catch(e){}throw new Error(d.message||`Could not upload ${file.name}`)}}
window.addRfiPhotos=async function(rfiId){modal(`<h2>Add Photos to RFI</h2><div class="field"><label>Photos</label><input id="rfi_photo_files" type="file" accept="image/*" multiple></div><div class="small">Choose one or multiple jobsite photos. You can add/edit each caption after upload.</div><div id="rfi_photo_status"></div><div class="actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button type="button" id="rfi_photo_upload" class="btn primary" onclick="uploadRfiPhotos('${rfiId}')">Upload Photos</button></div>`)};
window.uploadRfiPhotos=async function(rfiId){const input=q('rfi_photo_files'),files=[...(input?.files||[])];if(!files.length)return alert('Choose at least one photo.');const rfi=(await rest(`rfis?select=project_id&id=eq.${rfiId}&limit=1`))[0];if(!rfi)return alert('RFI not found.');const btn=q('rfi_photo_upload'),status=q('rfi_photo_status');btn.disabled=true;try{for(let i=0;i<files.length;i++){const f=files[i];if(!String(f.type||'').startsWith('image/'))throw new Error(`${f.name} is not an image.`);if(f.size>50*1024*1024)throw new Error(`${f.name} is larger than 50 MB.`);status.innerHTML=`<div class="notice success">Uploading ${i+1} of ${files.length}: ${esc(f.name)}</div>`;const path=`${rfi.project_id}/${rfiId}/photos/${Date.now()}-${i}-${safe(f.name)}`;await upload(path,f);await rest('rfi_photos',{method:'POST',body:JSON.stringify({rfi_id:rfiId,storage_path:path,caption:null,original_filename:f.name,mime_type:f.type||null,created_by:me.id})})}closeModal();await openRFI(rfiId)}catch(e){status.innerHTML=`<div class="notice">${esc(e.message||'Photo upload failed.')}</div>`;btn.disabled=false}};
window.editRfiPhotoCaption=async function(photoId,rfiId){try{const ph=(await rest(`rfi_photos?select=caption&id=eq.${photoId}&limit=1`))[0];if(!ph)return alert('Photo not found.');modal(`<h2>Photo Caption</h2><div class="field"><label>Caption</label><textarea id="rfi_photo_caption" rows="4" placeholder="Describe what this photo shows...">${esc(ph.caption||'')}</textarea></div><div id="rfi_caption_status"></div><div class="actions"><button type="button" class="btn secondary" onclick="closeModal()">Cancel</button><button type="button" class="btn primary" data-rfi-caption-save="1" data-photo-id="${esc(photoId)}" data-rfi-id="${esc(rfiId)}">Save Caption</button></div>`)}catch(e){alert(e.message||'Could not open photo caption.')}};
window.saveRfiPhotoCaption=async function(photoId,rfiId){const status=q('rfi_caption_status');try{const value=q('rfi_photo_caption')?.value.trim()||null;await rest(`rfi_photos?id=eq.${photoId}`,{method:'PATCH',body:JSON.stringify({caption:value})});closeModal();await openRFI(rfiId)}catch(e){if(status)status.innerHTML=`<div class="notice">${esc(e.message||'Could not save caption.')}</div>`;else alert(e.message||'Could not save caption.')}};
window.removeRfiPhoto=async function(photoId,rfiId){if(!confirm('Remove this photo from the RFI?'))return;const ph=(await rest(`rfi_photos?select=*&id=eq.${photoId}&limit=1`))[0];if(ph?.storage_path)await fetch(`${SB}/storage/v1/object/rfi-files/${enc(ph.storage_path)}`,{method:'DELETE',headers:{apikey:KEY,Authorization:'Bearer '+token}});await rest(`rfi_photos?id=eq.${photoId}`,{method:'DELETE'});openRFI(rfiId)};
window.addMoreDrawingToRfi=async function(rfiId){const r=(await rest(`rfis?select=project_id,rfi_number,subject&id=eq.${rfiId}&limit=1`))[0];if(!r)return;sessionStorage.setItem('sl_target_rfi',rfiId);alert(`Choose a drawing, tap RFI, mark up the page, then Complete Page and add it to RFI-${String(r.rfi_number).padStart(3,'0')}.`);go('drawings',r.project_id)};
async function install(id){const page=document.querySelector('.page');if(!page||q('sl_rfi_photos'))return;const photos=await rest(`rfi_photos?select=*&rfi_id=eq.${id}&order=created_at.asc`);for(const p of photos)if(p.storage_path){try{p.url=await sign(p.storage_path)}catch(e){p.url=''}}const drawingSection=[...page.querySelectorAll('.section')].find(x=>x.textContent.trim().startsWith('Marked-Up Drawing Pages'));if(!drawingSection)return;const wrap=document.createElement('div');wrap.id='sl_rfi_photos';wrap.innerHTML=`<div class="section">RFI Attachments</div><div class="actions"><button type="button" class="btn primary" onclick="addRfiPhotos('${id}')">+ Add Photos</button><button type="button" class="btn secondary" onclick="addMoreDrawingToRfi('${id}')">+ Add Drawing Page</button></div><div class="section">Photos (${photos.length})</div>${photos.map(p=>`<div class="card sl-rfi-attachment">${p.url?`<img class="sl-rfi-thumb" src="${p.url}" alt="RFI photo">`:''}<div class="sl-rfi-attachment-main"><div class="title">${esc(p.original_filename||'Photo')}</div><div class="small">${esc(p.caption||'No caption')}</div><div class="actions"><button type="button" class="btn secondary smallbtn" data-rfi-caption-edit="1" data-photo-id="${esc(p.id)}" data-rfi-id="${esc(id)}">${p.caption?'Edit Caption':'Add Caption'}</button><button type="button" class="sl-rfi-remove" onclick="removeRfiPhoto('${p.id}','${id}')">Remove</button></div></div></div>`).join('')||'<div class="card empty">No photos attached.</div>'}`;drawingSection.parentNode.insertBefore(wrap,drawingSection)}
document.addEventListener('click',function(e){const edit=e.target.closest('[data-rfi-caption-edit]');if(edit){e.preventDefault();e.stopPropagation();window.editRfiPhotoCaption(edit.dataset.photoId,edit.dataset.rfiId);return}const save=e.target.closest('[data-rfi-caption-save]');if(save){e.preventDefault();e.stopPropagation();window.saveRfiPhotoCaption(save.dataset.photoId,save.dataset.rfiId)}});
window.openRFI=async function(id){const out=await oldOpenRFI(id);requestAnimationFrame(()=>install(id).catch(console.error));return out};
})();