(function(){
const q=id=>document.getElementById(id);
const rfiLabel=r=>`RFI-${String(r.rfi_number).padStart(3,'0')}`;
async function projectRFIs(pid){return rest(`rfis?select=*&project_id=eq.${pid}&order=rfi_number.desc`)}
async function nextNo(pid){const rows=await rest(`rfis?select=rfi_number&project_id=eq.${pid}&order=rfi_number.desc&limit=1`);return (rows[0]?.rfi_number||0)+1}
window.openProjectRFIs=async function(pid){route.screen='rfis';route.projectId=pid;loading('Loading RFIs…');const p=(await rest(`projects?select=*&id=eq.${pid}&limit=1`))[0],rows=await projectRFIs(pid);const counts={open:0,overdue:0,answered:0,closed:0,draft:0};rows.forEach(r=>{counts[r.status]=(counts[r.status]||0)+1;if(r.due_date&&r.due_date<today&&!['answered','closed'].includes(r.status))counts.overdue++});shell('RFIs',`<button class="btn secondary smallbtn" onclick="go('project','${pid}')">← Project</button><div class="hero"><div class="eyebrow">${esc(p?.name||'Project')}</div><h1>RFI Log</h1><p>Drawing-linked requests for information and responses.</p></div><div class="metrics"><div class="metric"><b>${counts.open}</b><span>Open</span></div><div class="metric"><b>${counts.overdue}</b><span>Overdue</span></div><div class="metric"><b>${counts.answered}</b><span>Answered</span></div><div class="metric"><b>${counts.closed}</b><span>Closed</span></div></div><button class="btn primary block" onclick="newProjectRFI('${pid}')">+ New RFI</button><div class="section">All RFIs</div>${rows.map(r=>`<div class="card click" onclick="openRFI('${r.id}')"><div class="row"><div><div class="title">${rfiLabel(r)} · ${esc(r.subject)}</div><div class="small">${esc(r.assigned_to||'Unassigned')}${r.due_date?' · Due '+esc(r.due_date):''}</div></div><span class="badge ${r.status==='closed'?'done':r.status==='answered'?'up':r.status==='draft'?'':'due'}">${esc(r.status.toUpperCase())}</span></div></div>`).join('')||'<div class="card empty">No RFIs yet.</div>'}`,'projects')}
window.newProjectRFI=async function(pid,markupId=''){const n=await nextNo(pid);modal(`<h2>New RFI-${String(n).padStart(3,'0')}</h2><div class="field"><label>Subject</label><input id="rfi_subject" placeholder="Ceiling detail clarification"></div><div class="field"><label>Question / Request</label><textarea id="rfi_question" rows="5" placeholder="Describe exactly what needs clarification..."></textarea></div><div class="field"><label>Suggested Solution <span class="small">(optional)</span></label><textarea id="rfi_solution" rows="3"></textarea></div><div class="grid2"><div class="field"><label>To</label><input id="rfi_to" placeholder="Architect / Engineer"></div><div class="field"><label>Due Date</label><input id="rfi_due" type="date"></div></div><div class="actions"><button class="btn secondary" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveProjectRFI('${pid}',${n},'${markupId}')">Create RFI</button></div>`)}
window.saveProjectRFI=async function(pid,n,markupId=''){const subject=q('rfi_subject').value.trim();if(!subject)return alert('Enter an RFI subject.');const rows=await rest('rfis',{method:'POST',body:JSON.stringify({project_id:pid,rfi_number:n,subject,question:q('rfi_question').value.trim()||null,suggested_solution:q('rfi_solution').value.trim()||null,assigned_to:q('rfi_to').value.trim()||null,due_date:q('rfi_due').value||null,status:'draft',created_by:me.id})});if(markupId)await rest(`drawing_markups?id=eq.${markupId}`,{method:'PATCH',body:JSON.stringify({rfi_id:rows[0].id,reference_no:rfiLabel(rows[0]),status:'open'})});closeModal();openRFI(rows[0].id)}
window.openRFI=async function(id){loading('Opening RFI…');const r=(await rest(`rfis?select=*&id=eq.${id}&limit=1`))[0];if(!r)return alert('RFI not found.');const p=(await rest(`projects?select=*&id=eq.${r.project_id}&limit=1`))[0];const marks=await rest(`drawing_markups?select=*,drawing_sheets(page_number,drawings(title,drawing_number))&rfi_id=eq.${id}&order=created_at`);shell(rfiLabel(r),`<button class="btn secondary smallbtn" onclick="openProjectRFIs('${r.project_id}')">← RFI Log</button><div class="hero"><div class="eyebrow">${esc(p?.name||'')}</div><h1>${rfiLabel(r)} · ${esc(r.subject)}</h1><p>${esc(r.status.toUpperCase())}${r.due_date?' · Due '+esc(r.due_date):''}</p></div><div class="card"><div class="section">Question / Request</div><div>${esc(r.question||'No question entered.')}</div>${r.suggested_solution?`<div class="section">Suggested Solution</div><div>${esc(r.suggested_solution)}</div>`:''}<div class="section">To</div><div>${esc(r.assigned_to||'Not assigned')}</div></div><div class="section">Drawing References (${marks.length})</div>${marks.map(m=>`<div class="card"><div class="title">${esc(m.drawing_sheets?.drawings?.drawing_number||'Drawing')} · Page ${m.drawing_sheets?.page_number||''}</div><div class="small">${esc(m.title||m.content||'RFI markup')}</div></div>`).join('')||'<div class="card empty">No drawing markups attached yet.</div>'}<div class="section">Response</div><div class="card"><textarea id="rfi_response" rows="5" placeholder="Enter architect/engineer response...">${esc(r.response||'')}</textarea><div class="actions"><button class="btn secondary" onclick="setRFIStatus('${id}','open')">Open</button><button class="btn secondary" onclick="saveRFIResponse('${id}')">Save Answer</button><button class="btn primary" onclick="setRFIStatus('${id}','closed')">Close RFI</button></div></div>`,'projects')}
window.saveRFIResponse=async id=>{await rest(`rfis?id=eq.${id}`,{method:'PATCH',body:JSON.stringify({response:q('rfi_response').value.trim()||null,status:'answered',answered_at:new Date().toISOString(),updated_at:new Date().toISOString()})});openRFI(id)};
window.setRFIStatus=async(id,status)=>{const b={status,updated_at:new Date().toISOString()};if(status==='closed')b.closed_at=new Date().toISOString();if(status==='open')b.sent_at=new Date().toISOString();await rest(`rfis?id=eq.${id}`,{method:'PATCH',body:JSON.stringify(b)});openRFI(id)};
window.chooseRFIForMarkup=async function(markupId,pid){const rows=await projectRFIs(pid);modal(`<h2>Add Drawing Markup to RFI</h2><button class="btn primary block" onclick="newProjectRFI('${pid}','${markupId}')">+ Create New RFI</button><div class="section">Or add to existing</div>${rows.filter(r=>r.status!=='closed').map(r=>`<button class="btn secondary block rfi-choice" onclick="attachMarkupToRFI('${markupId}','${r.id}','${rfiLabel(r)}')"><b>${rfiLabel(r)}</b> · ${esc(r.subject)}</button>`).join('')||'<div class="card empty">No open RFIs.</div>'}<div class="actions"><button class="btn secondary" onclick="closeModal()">Cancel</button></div>`)};
window.attachMarkupToRFI=async(markupId,rfiId,label)=>{await rest(`drawing_markups?id=eq.${markupId}`,{method:'PATCH',body:JSON.stringify({rfi_id:rfiId,reference_no:label,status:'open'})});closeModal();if(window.refreshDrawingAnnotations)window.refreshDrawingAnnotations()};
function addProjectButton(){if(route?.screen!=='project'||!route.projectId)return;const page=document.querySelector('.page');if(!page||q('sl_project_rfis'))return;const sections=[...page.querySelectorAll('.section')];const target=sections.find(x=>x.textContent.trim()==='This Week');if(target)target.insertAdjacentHTML('beforebegin',`<div id="sl_project_rfis"><div class="section">Project Management</div><button class="btn secondary block" onclick="openProjectRFIs('${route.projectId}')">RFIs →</button></div>`)}
new MutationObserver(()=>requestAnimationFrame(addProjectButton)).observe(document.getElementById('app'),{childList:true,subtree:true});addProjectButton();
})();