const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const root=path.join(__dirname,'..');
const html=fs.readFileSync(path.join(root,'www/index.html'),'utf8');
assert(!html.includes('serviceWorker'),'native bundle cannot register a web service worker');
assert(html.includes('<title>RAF Construction Management</title>'));
assert(html.indexOf('native.js')<html.indexOf('app.js'),'native integrations load before app startup');
for(const m of html.matchAll(/(?:src|href)="([^"?#]+)(?:\?[^"#]*)?"/g))assert(fs.existsSync(path.join(root,'www',m[1])),m[1]+' is bundled');
for(const name of ['pdf.min.js','pdf.worker.min.mjs','jspdf.umd.min.js','jszip.min.js'])assert(fs.statSync(path.join(root,'www/vendor',name)).size>1000);
new vm.Script(fs.readFileSync(path.join(root,'www/native.js'),'utf8'));
const config=JSON.parse(fs.readFileSync(path.join(root,'capacitor.config.json'),'utf8'));
assert(!config.server?.url,'production app must use installed assets');
assert(!fs.readFileSync(path.join(root,'www/team-management.js'),'utf8').includes('${location.origin}${location.pathname}'),'native invitations use the public web address');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const checked=index.match(/getItem\('(sl_sw_reloaded_[^']+)'\)/)[1];
assert(index.includes("setItem('"+checked+"'"),'update reload guard writes the same key it checks');
console.log('PASS mobile asset packaging, native startup, local PDF tools and update reload guard');
